gbsteps: &gbsteps
  steps:
    - run:
        name: Report on build environment
        command: |
          java -version
          javac -version

    - checkout
    - run: ant

    - run: ant test
    - run:
        name: Collect test results
        command: |
          mkdir -p test_reports/junit/
          cp -a build/tests/TEST-*.xml test_reports/junit/
    - store_test_results:
        path: test_reports
    - store_artifacts:
        path:  build/target/reports


version: 2

jobs:
  buildJ8:
    docker:
      - image: circleci/openjdk:8-jdk

    <<: *gbsteps

  buildJ9:
    docker:
      - image: circleci/openjdk:9-jdk

    <<: *gbsteps

  buildJ11:
    docker:
      - image: circleci/openjdk:11-jdk

    <<: *gbsteps

workflows:
  version: 2
  build:
    jobs:
      - "buildJ8"
      - "buildJ9"
      - "buildJ11"
